Repository XxArcticAssassinxX/textbasedturncombatgame, pull requests merged in 2020-05, with the labels that each got.

#2 Structure Changes
  README.md
  main.py
Labels: enhancement

#4 Issue Quick Fixes
  main.py
Labels: bug

#9 Morganzwest issue fix 1
  .idea/.gitignore
  .idea/dictionaries/Morgan.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/textbasedturncombatgame.iml
  .idea/vcs.xml
  main.py
Labels: bug

#12 Updated Kill Output
  main.py
Labels: bug

#19 Updated versions
  main.py
Labels: enhancement

#20 Autonomised Version Switching - 0.2.43v.DV
  main.py
Labels: enhancement

#22 Update version
  main.py
Labels: documentation
